'''
This code generated by Google AI to demonstrate cv2.circle function
'''
import cv2
import numpy as np

# Create a black image
image = np.ones((512, 512, 3), dtype=np.uint8)

# Circle parameters
center_coordinates = (256, 256)
radius = 285
color = (255, 255, 255)
thickness = 2

# Draw the circle
cv2.circle(image, center_coordinates, radius, color, thickness)

# Display the image
cv2.imshow('Circle Image', image)
cv2.waitKey(0)
cv2.destroyAllWindows()
