# Original code generated by Google AI
# Displays a mess of 'Camera index out of range' messages and then
#   displays 'Available cameras:  Camera index 0'
import cv2

def list_ports():
    available_ports = []
    for i in range(10): # Check up to 10 ports
        cap = cv2.VideoCapture(i)
        if cap.isOpened():
            available_ports.append(i)
            cap.release()
    return available_ports

if __name__ == "__main__":
    ports = list_ports()
    if ports:
        print("Available cameras:")
        for port in ports:
            print(f"Camera index {port}")
    else:
        print("No cameras found")